apiVersion: troubleshoot.replicated.com/v1beta1
kind: Analyzer
metadata:
  name: ethan-kots
spec:
  analyzers:
    - deploymentStatus:
        name: nginx
        outcomes:
          - fail:
              when: "< 1"
              message: The Nginx deployment does not have any ready replicas.
          - warn:
              when: "= 1"
              message: The Nginx deployment has only a single ready replica.
          - pass:
              message: There are multiple replicas of the Nginx deployment ready.
    - clusterVersion:
        outcomes:
          - fail:
              when: "< 1.13.0"
              message: Ethan Kots requires at Kubernetes 1.13.0 or later, and recommends 1.15.0.
              uri: https://www.kubernetes.io
          - warn:
              when: "< 1.15.0"
              message: Your cluster meets the minimum version of Kubernetes, but we recommend you update to 1.15.0 or later.
              uri: https://kubernetes.io
          - pass:
              message: Your cluster meets the recommended and required versions of Kubernetes.
    - customResourceDefinition:
        customResourceDefinitionName: ingressroutes.contour.heptio.com
        outcomes:
          - fail:
              message: IngressRoutes CRD not found!
          - pass:
              message: IngressRoutes CRD found!
